python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Food_Allergy_superfinal_20250117_171302.json"
python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Allergic_Rhinitis_Hay_Fever_superfinal_20250117_171123.json"
python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Drug_Allergies_superfinal_20250117_180851.json"
python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Atopic_Dermatitis_Eczema_superfinal_20250117_171306.json"
python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Contact_Dermatitis_superfinal_20250117_145902.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Ankylosing_Spondylitis_superfinal_20250117_171328.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Gout_superfinal_20250117_171438.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/GuillainBarre_Syndrome_superfinal_20250117_171501.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Multiple_Sclerosis_MS_superfinal_20250117_171906.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Osteoarthritis_superfinal_20250117_171904.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Rheumatoid_Arthritis_superfinal_20250117_172148.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sarcoidosis_superfinal_20250117_172135.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Scleroderma_superfinal_20250117_180848.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Systemic_Lupus_Erythematosus_SLE_superfinal_20250117_172405.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Vasculitis_superfinal_20250117_172638.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Ant_Bites_superfinal_20250117_172555.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Bedbug_Bites_superfinal_20250117_172705.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Flea_Bites_superfinal_20250117_172749.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Horsefly_Bites_superfinal_20250117_172610.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Mosquito_Bites_superfinal_20250117_173047.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Spider_Bites_superfinal_20250117_173304.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Tick_Bites_superfinal_20250117_173424.json"
python manage.py import_articles --category-name "Blood Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Anemia_superfinal_20250117_173916.json"
python manage.py import_articles --category-name "Blood Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hemophilia_superfinal_20250117_173645.json"
python manage.py import_articles --category-name "Blood Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Thrombocytopenia_Low_Platelet_Count_superfinal_20250117_173811.json"
python manage.py import_articles --category-name "Blood Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Polycythemia_Vera_superfinal_20250117_173738.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Osteoporosis_superfinal_20250117_181124.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Osteomalacia_Soft_Bone_Disease_superfinal_20250117_181414.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Osteogenesis_Imperfecta_Brittle_Bone_Disease_superfinal_20250117_181127.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Pagets_Disease_of_Bone_Osteitis_Deformans_superfinal_20250117_181137.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Bone_Fractures_superfinal_20250117_181836.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Basal_Cell_Carcinoma_superfinal_20250117_181740.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Breast_Cancer_superfinal_20250117_182821.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Cervical_Cancer_superfinal_20250117_182339.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Colorectal_Cancer_superfinal_20250117_182255.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Liver_Cancer_superfinal_20250117_182541.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Lung_Cancer_superfinal_20250117_182623.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Melanoma_superfinal_20250117_182825.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Ovarian_Cancer_superfinal_20250117_183317.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Prostate_Cancer_superfinal_20250117_183339.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Squamous_Cell_Carcinoma_superfinal_20250117_183335.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Leukemia_Blood_Cancer_superfinal_20250117_183528.json"
python manage.py import_articles --category-name "Cardiovascular" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Cardiac_Arrhythmia_superfinal_20250117_183827.json"
python manage.py import_articles --category-name "Cardiovascular" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Coronary_Artery_Disease_superfinal_20250117_183317.json"
python manage.py import_articles --category-name "Cardiovascular" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Heart_Failure_superfinal_20250117_184526.json"
python manage.py import_articles --category-name "Cardiovascular" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hypertension_High_Blood_Pressure_superfinal_20250117_183949.json"
python manage.py import_articles --category-name "Chronic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Chronic_Fatigue_Syndrome_superfinal_20250117_184219.json"
python manage.py import_articles --category-name "Chronic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Fibromyalgia_superfinal_20250117_184134.json"
python manage.py import_articles --category-name "Chronic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/PostCOVID_Syndrome_Long_COVID_superfinal_20250117_184917.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Anal_Fissures_superfinal_20250117_184457.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Appendicitis_superfinal_20250117_184624.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Barretts_Esophagus_superfinal_20250117_185050.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Celiac_Disease_superfinal_20250117_184746.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Colitis_superfinal_20250117_185138.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Constipation_superfinal_20250117_185413.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Crohns_Disease_Intestinal_Inflammation_superfinal_20250117_185625.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Diarrhea_superfinal_20250117_190453.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Esophagitis_superfinal_20250117_190137.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Functional_Dyspepsia_superfinal_20250117_190101.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Gallbladder_Disease_superfinal_20250117_190429.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Gastritis_superfinal_20250117_190321.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Gastroenteritis_Stomach_Flu_superfinal_20250117_190342.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Gastroesophageal_Reflux_Disease_GERD_superfinal_20250117_191538.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Gastroparesis_superfinal_20250117_191024.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hemorrhoids_Piles_superfinal_20250117_191311.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Inflammatory_Bowel_Disease_IBD_superfinal_20250117_191327.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Irritable_Bowel_Syndrome_IBS_superfinal_20250117_191407.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Lactose_Intolerance_superfinal_20250117_191232.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Pancreatitis_superfinal_20250117_191529.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Small_Intestinal_Bacterial_Overgrowth_SIBO_superfinal_20250117_192427.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/ZollingerEllison_Syndrome_superfinal_20250117_192431.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Otitis_Externa_Swimmers_Ear_superfinal_20250117_192144.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Tonsillitis_superfinal_20250117_192405.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Eustachian_Tube_Dysfunction_Eustachian_Tube_Disorder_superfinal_20250117_192618.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Laryngitis_superfinal_20250117_192602.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Tympanic_Membrane_Eardrum_Perforation_superfinal_20250117_193210.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Eustachian_Tube_Dysfunction_ETD_superfinal_20250117_193147.json"
python manage.py import_articles --category-name "Endocrine & Metabolic" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hashimotos_Thyroiditis_Autoimmune_Thyroiditis_superfinal_20250117_193028.json"
python manage.py import_articles --category-name "Endocrine & Metabolic" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hyperthyroidism_superfinal_20250117_193421.json"
python manage.py import_articles --category-name "Endocrine & Metabolic" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Type_1_Diabetes_superfinal_20250117_193235.json"
python manage.py import_articles --category-name "Endocrine & Metabolic" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Type_2_Diabetes_superfinal_20250117_193826.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Agerelated_Macular_Degeneration_AMD_superfinal_20250117_194237.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Amblyopia_superfinal_20250117_194210.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Astigmatism_superfinal_20250117_194355.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Blepharitis_superfinal_20250117_194147.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Conjunctivitis_superfinal_20250117_111620.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Diabetic_Retinopathy_superfinal_20250117_111638.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Dry_Eye_Syndrome_Dry_Eye_superfinal_20250117_111554.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Eye_Floaters_superfinal_20250117_194543.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Glaucoma_superfinal_20250117_111908.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hyperopia_Farsightedness_superfinal_20250117_111419.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Keratitis_superfinal_20250117_111935.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Keratoconus_superfinal_20250117_112111.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Macular_Hole_superfinal_20250117_112045.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Myopia_Nearsightedness_superfinal_20250117_112414.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Photophobia_superfinal_20250117_112425.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Presbyopia_superfinal_20250117_112522.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Retinal_Detachment_superfinal_20250117_155135.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Retinitis_Pigmentosa_superfinal_20250117_112856.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Strabismus_superfinal_20250117_113005.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Uveitis_superfinal_20250117_113433.json"
python manage.py import_articles --category-name "Genetic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Cystic_Fibrosis_superfinal_20250117_113409.json"
python manage.py import_articles --category-name "Genetic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Huntingtons_Disease_superfinal_20250117_113344.json"
python manage.py import_articles --category-name "Genetic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sickle_Cell_Disease_superfinal_20250117_113609.json"
python manage.py import_articles --category-name "Genetic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Marfan_Syndrome_superfinal_20250117_113719.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Yeast_Infection_Candidiasis_superfinal_20250117_113723.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Chickenpox_and_Shingles_VaricellaZoster_Virus_Infection_superfinal_20250117_113846.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Clostridioides_difficile_C_diff_Infection_superfinal_20250117_113845.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Common_Cold_superfinal_20250117_114032.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/HIVAIDS_superfinal_20250117_114127.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hepatitis_B_HBV_superfinal_20250117_114411.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hepatitis_C_HCV_superfinal_20250117_114303.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Herpes_Simplex_Virus_Infection_HSV_superfinal_20250117_114647.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Human_Papillomavirus_HPV_Infection_superfinal_20250117_114513.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Influenza_Flu_superfinal_20250117_114802.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Lyme_Disease_superfinal_20250117_114844.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Meningitis_superfinal_20250117_115305.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Mononucleosis_Mono_superfinal_20250117_115133.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Osteomyelitis_Bone_Infection_superfinal_20250117_120317.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sepsis_superfinal_20250117_115407.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Streptococcal_Pharyngitis_Strep_throat_superfinal_20250117_115558.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Tuberculosis_superfinal_20250117_115714.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Chronic_Kidney_Disease_CKD_superfinal_20250117_120306.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Cirrhosis_superfinal_20250117_120406.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hepatitis_superfinal_20250117_120456.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/MetabolicAssociated_Steatohepatitis_superfinal_20250117_120250.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/MetabolicAssociated_Steatotic_Liver_Disease_superfinal_20250117_120445.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/AttentionDeficitHyperactivity_Disorder_ADHD_superfinal_20250117_121316.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Anxiety_Disorder_superfinal_20250117_121207.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Aspergers_Syndrome_superfinal_20250117_121101.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Autism_Spectrum_Disorder_superfinal_20250117_121234.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Bipolar_Disorder_superfinal_20250117_121511.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Depression_superfinal_20250117_121421.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Loneliness_superfinal_20250117_121820.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Panic_Disorder_superfinal_20250117_121836.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Postpartum_Depression_superfinal_20250117_121845.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Seasonal_Affective_Disorder_superfinal_20250117_122135.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Childhood_Obesity_superfinal_20250117_122149.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Dyslipidemia_superfinal_20250117_122137.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Metabolic_Syndrome_superfinal_20250117_122559.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Obesity_superfinal_20250117_122738.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Prediabetes_superfinal_20250117_122517.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Achilles_Tendinitis_Achilles_Tendinopathy_superfinal_20250117_122828.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Acute_fractures_superfinal_20250117_123350.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Ankle_Sprain_superfinal_20250117_122820.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Anterior_Cruciate_Ligament_Tear_ACL_Tear_superfinal_20250117_123419.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Bruises_Contusion_superfinal_20250117_123438.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Burns_superfinal_20250117_123638.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Bursitis_superfinal_20250117_123835.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Frostbite_superfinal_20250117_123937.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Medial_Epicondylitis_Golfers_Elbow_superfinal_20250117_123823.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Growth_Plate_Fracture_superfinal_20250117_124018.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hamstring_Injury_superfinal_20250117_124143.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Herniated_Disc_superfinal_20250117_124645.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Iliotibial_Band_Syndrome_superfinal_20250117_124429.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Glenoid_Labrum_Tear_superfinal_20250117_124642.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Little_League_Elbow_superfinal_20250117_125711.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Little_League_Shoulder_superfinal_20250117_124609.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Medial_Collateral_Ligament_Injury_superfinal_20250117_124917.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Muscle_Cramp_superfinal_20250117_125228.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/OsgoodSchlatter_Disease_superfinal_20250117_125626.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Osteochondritis_Dissecans_superfinal_20250117_125526.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Overtraining_Syndrome_superfinal_20250117_125556.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Repetitive_Strain_Injury_superfinal_20250117_130459.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Patellar_Tendinitis_superfinal_20250117_130129.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Patellofemoral_Pain_Syndrome_PFPS_superfinal_20250117_130245.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sacroiliac_Joint_Dysfunction_Pelvic_Pain_superfinal_20250117_130936.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Plantar_Fasciitis_superfinal_20250117_130857.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Rotator_Cuff_Tear_superfinal_20250117_130455.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Scoliosis_superfinal_20250117_131009.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Severs_Disease_Calcaneal_Apophysitis_superfinal_20250117_130842.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Medial_Tibial_Stress_Syndrome_Shin_Splints_superfinal_20250117_131507.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Shoulder_Dislocation_superfinal_20250117_194927.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Spinal_Stenosis_superfinal_20250117_131522.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Spondylolisthesis_superfinal_20250117_131844.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sprains_and_Strains_superfinal_20250117_131946.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Stress_Fracture_superfinal_20250117_131900.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Lateral_Epicondylitis_Tennis_Elbow_superfinal_20250117_131757.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Meniscus_Tear_superfinal_20250117_132538.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Alzheimers_Disease_superfinal_20250117_155021.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Carpal_Tunnel_Syndrome_superfinal_20250117_132829.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Cervical_Radiculopathy_superfinal_20250117_132721.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Cluster_Headache_superfinal_20250117_132947.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Concussions_superfinal_20250117_132918.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/ICU_Delirium_superfinal_20250117_132843.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Lumbar_Radiculopathy_superfinal_20250117_133315.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Migraine_Headache_superfinal_20250117_133411.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Postural_Orthostatic_Tachycardia_Syndrome_POTS_superfinal_20250117_133631.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Parkinsons_Disease_superfinal_20250117_133921.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Peripheral_Neuropathy_superfinal_20250117_134139.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Postherpetic_Neuralgia_Shingles_Pain_superfinal_20250117_133931.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sciatica_superfinal_20250117_134259.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Stroke_superfinal_20250117_134116.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Tension_Headache_superfinal_20250117_134235.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Trigeminal_Neuralgia_superfinal_20250117_134536.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Vertigo_superfinal_20250117_134522.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Visual_Migraine_Ocular_Migraine_superfinal_20250117_134708.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Halitosis_Bad_Breath_superfinal_20250117_134935.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Cavities_Tooth_Decay_superfinal_20250117_135144.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Dental_Abscess_superfinal_20250117_155050.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Dry_Mouth_Xerostomia_superfinal_20250117_135542.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Gingivitis_superfinal_20250117_135300.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Mouth_Ulcers_Canker_Sores_superfinal_20250117_135656.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Orthodontic_Relapse_superfinal_20250117_135300.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Periodontitis_superfinal_20250117_135910.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Dentin_Hypersensitivity_Tooth_Sensitivity_superfinal_20250117_135702.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Wisdom_Teeth_Impaction_superfinal_20250117_135950.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Malaria_superfinal_20250117_140246.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Toxoplasmosis_superfinal_20250117_140118.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Giardiasis_superfinal_20250117_155137.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Trichinosis_superfinal_20250117_140439.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Lice_Infestation_Pediculosis_superfinal_20250117_140950.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Scabies_superfinal_20250117_140512.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Endometriosis_superfinal_20250117_141028.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Infertility_superfinal_20250117_141817.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Menopause_Menopausal_Symptoms_superfinal_20250117_141234.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Menstrual_Disorders_superfinal_20250117_142159.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Polycystic_Ovary_Syndrome_PCOS_Related_Hair_Loss_superfinal_20250117_141743.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Polycystic_Ovary_Syndrome_PCOS_superfinal_20250117_141944.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Premenstrual_Dysphoric_Disorder_superfinal_20250117_141941.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Premenstrual_Syndrome_superfinal_20250117_155346.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Acute_Respiratory_Distress_Syndrome_ARDS_superfinal_20250117_142513.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Asthma_superfinal_20250117_143331.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Bronchitis_superfinal_20250117_143046.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Chronic_Cough_superfinal_20250117_143135.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Chronic_Obstructive_Pulmonary_Disease_COPD_superfinal_20250117_142707.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Lung_Abscess_superfinal_20250117_143329.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Occupational_Lung_Disease_superfinal_20250117_143203.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Pneumoconiosis_superfinal_20250117_143731.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Pneumonia_superfinal_20250117_143941.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Pulmonary_Embolism_superfinal_20250117_144239.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Pulmonary_Fibrosis_superfinal_20250117_144212.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Pulmonary_Hypertension_superfinal_20250117_144303.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sinusitis_Sinus_Infection_superfinal_20250117_144301.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Bacterial_Vaginosis_BV_superfinal_20250117_144247.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Chlamydia_Infection_superfinal_20250117_144421.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Gonorrhea_superfinal_20250117_145235.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Syphilis_superfinal_20250117_144944.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Trichomoniasis_superfinal_20250117_144913.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Acne_Vulgaris_Acne_Vulgaris_superfinal_20250117_145325.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Actinic_Keratosis_superfinal_20250117_145206.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Albinism_superfinal_20250117_145413.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Alopecia_Areata_superfinal_20250117_145530.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Athletes_Foot_Tinea_Pedis_superfinal_20250117_145542.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Boils_Furuncle_superfinal_20250117_145938.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Cellulitis_superfinal_20250117_145726.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Contact_Dermatitis_superfinal_20250117_145902.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Cystic_Acne_superfinal_20250117_150056.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Eczema_Atopic_Dermatitis_superfinal_20250117_150116.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Folliculitis_superfinal_20250117_150412.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Alopecia_Hair_Loss_superfinal_20250117_150734.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Urticaria_Hives_superfinal_20250117_150633.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Hyperhidrosis_superfinal_20250117_150702.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Tinea_Cruris_Jock_Itch_superfinal_20250117_150651.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Keloid_superfinal_20250117_150921.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Keratosis_Pilaris_superfinal_20250117_151016.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Melasma_superfinal_20250117_151303.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Postpartum_Hair_Loss_superfinal_20250117_151414.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Psoriasis_superfinal_20250117_151646.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Ringworm_Tinea_superfinal_20250117_151646.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Rosacea_superfinal_20250117_151949.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Seborrheic_Dermatitis_superfinal_20250117_151834.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Skin_Tag_Acrochordon_superfinal_20250117_152015.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sunburn_superfinal_20250117_151957.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Vitiligo_superfinal_20250117_152525.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Wart_superfinal_20250117_194703.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Central_Sleep_Apnea_CSA_superfinal_20250117_152445.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Delayed_Sleep_Phase_Syndrome_superfinal_20250117_152346.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Familial_Advanced_Sleep_Phase_Syndrome_superfinal_20250117_152516.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Idiopathic_Hypersomnia_superfinal_20250117_152709.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Insomnia_superfinal_20250117_155552.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Narcolepsy_superfinal_20250117_155824.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Night_Terrors_superfinal_20250117_155704.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Non24Hour_SleepWake_Disorder_superfinal_20250117_155831.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Periodic_Limb_Movement_Disorder_PLMD_superfinal_20250117_155757.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/REM_Sleep_Behavior_Disorder_superfinal_20250117_160050.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Restless_Legs_Syndrome_superfinal_20250117_160620.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Shift_Work_Sleep_Disorder_superfinal_20250117_160434.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sleep_Apnea_superfinal_20250117_160659.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sleep_Bruxism_Teeth_Grinding_superfinal_20250117_160445.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Sleepwalking_superfinal_20250117_160712.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Interstitial_Cystitis_superfinal_20250117_160806.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Urinary_Tract_Infection_UTI_superfinal_20250117_160924.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Nephrolithiasis_Kidney_Stones_superfinal_20250117_161116.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Urinary_Incontinence_superfinal_20250117_161137.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/filtered_json/Prostatitis_superfinal_20250117_161352.json"
