python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Food_Allergy_final_20250127_142027.json"
python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Allergic_Rhinitis_Hay_Fever_final_20250127_141747.json"
python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Drug_Allergies_final_20250127_141936.json"
python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Atopic_Dermatitis_Eczema_final_20250127_141950.json"
python manage.py import_articles --category-name "Allergies" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Contact_Dermatitis_final_20250127_182750.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Ankylosing_Spondylitis_final_20250127_142053.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Gout_final_20250127_142223.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/GuillainBarre_Syndrome_final_20250127_142434.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Multiple_Sclerosis_MS_final_20250127_142414.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Osteoarthritis_final_20250127_142637.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Rheumatoid_Arthritis_final_20250127_142545.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sarcoidosis_final_20250127_142708.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Scleroderma_final_20250127_142756.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Systemic_Lupus_Erythematosus_SLE_final_20250127_142921.json"
python manage.py import_articles --category-name "Autoimmune & Inflammatory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Vasculitis_final_20250127_143225.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Ant_Bites_final_20250127_142850.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Bedbug_Bites_final_20250127_143041.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Flea_Bites_final_20250127_143118.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Horsefly_Bites_final_20250127_143102.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Mosquito_Bites_final_20250127_143216.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Spider_Bites_final_20250127_143417.json"
python manage.py import_articles --category-name "Bites & Stings" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Tick_Bites_final_20250127_143716.json"
python manage.py import_articles --category-name "Blood Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Anemia_final_20250127_143729.json"
python manage.py import_articles --category-name "Blood Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hemophilia_final_20250127_143615.json"
python manage.py import_articles --category-name "Blood Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Thrombocytopenia_Low_Platelet_Count_final_20250127_143808.json"
python manage.py import_articles --category-name "Blood Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Polycythemia_Vera_final_20250127_143840.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Osteoporosis_final_20250127_144105.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Osteomalacia_Soft_Bone_Disease_final_20250127_144213.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Osteogenesis_Imperfecta_Brittle_Bone_Disease_final_20250127_144046.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Pagets_Disease_of_Bone_Osteitis_Deformans_final_20250127_144244.json"
python manage.py import_articles --category-name "Bone Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Bone_Fractures_final_20250127_144347.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Basal_Cell_Carcinoma_final_20250127_144513.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Breast_Cancer_final_20250127_144603.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cervical_Cancer_final_20250127_144711.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Colorectal_Cancer_final_20250127_144645.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Liver_Cancer_final_20250127_144831.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Lung_Cancer_final_20250127_144833.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Melanoma_final_20250127_145030.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Ovarian_Cancer_final_20250127_145452.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Prostate_Cancer_final_20250127_145218.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Squamous_Cell_Carcinoma_final_20250127_145313.json"
python manage.py import_articles --category-name "Cancer" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Leukemia_Blood_Cancer_final_20250127_145325.json"
python manage.py import_articles --category-name "Cardiovascular" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cardiac_Arrhythmia_final_20250127_145515.json"
python manage.py import_articles --category-name "Cardiovascular" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Coronary_Artery_Disease_final_20250127_145646.json"
python manage.py import_articles --category-name "Cardiovascular" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Heart_Failure_final_20250127_145912.json"
python manage.py import_articles --category-name "Cardiovascular" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hypertension_High_Blood_Pressure_final_20250127_145853.json"
python manage.py import_articles --category-name "Chronic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Chronic_Fatigue_Syndrome_final_20250127_145945.json"
python manage.py import_articles --category-name "Chronic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Fibromyalgia_final_20250127_150002.json"
python manage.py import_articles --category-name "Chronic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/PostCOVID_Syndrome_Long_COVID_final_20250127_150221.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Anal_Fissures_final_20250127_150127.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Appendicitis_final_20250127_150259.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Barretts_Esophagus_final_20250127_150438.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Celiac_Disease_final_20250127_150425.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cholecystitis_final_20250127_150523.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Colitis_final_20250127_150739.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Constipation_final_20250127_150705.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Crohns_Disease_Intestinal_Inflammation_final_20250127_151028.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Diarrhea_final_20250127_150841.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Diverticulitis_final_20250127_150901.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Esophagitis_final_20250127_151142.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Functional_Dyspepsia_final_20250127_151356.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Gallbladder_Disease_final_20250127_151314.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Gastritis_final_20250127_151248.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Gastroenteritis_Stomach_Flu_final_20250127_151350.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Gastroesophageal_Reflux_Disease_GERD_final_20250127_151548.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Gastroparesis_final_20250127_151650.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hemorrhoids_Piles_final_20250127_151613.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Inflammatory_Bowel_Disease_IBD_final_20250127_152003.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Irritable_Bowel_Syndrome_IBS_final_20250127_151926.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Lactose_Intolerance_final_20250127_151953.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Pancreatitis_final_20250127_152153.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Peptic_Ulcer_Disease_PUD_final_20250127_152057.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Small_Intestinal_Bacterial_Overgrowth_SIBO_final_20250127_152819.json"
python manage.py import_articles --category-name "Digestive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/ZollingerEllison_Syndrome_final_20250127_152537.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Otitis_Externa_Swimmers_Ear_final_20250127_152412.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Tonsillitis_final_20250127_152604.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Eustachian_Tube_Dysfunction_Eustachian_Tube_Disorder_final_20250127_152620.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Laryngitis_final_20250127_152710.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Tympanic_Membrane_Eardrum_Perforation_final_20250127_152755.json"
python manage.py import_articles --category-name "Ear & Throat Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Eustachian_Tube_Dysfunction_ETD_final_20250127_152932.json"
python manage.py import_articles --category-name "Endocrine & Metabolic" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hashimotos_Thyroiditis_Autoimmune_Thyroiditis_final_20250127_152943.json"
python manage.py import_articles --category-name "Endocrine & Metabolic" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hyperthyroidism_final_20250127_153156.json"
python manage.py import_articles --category-name "Endocrine & Metabolic" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hypothyroidism_final_20250127_153300.json"
python manage.py import_articles --category-name "Endocrine & Metabolic" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Type_1_Diabetes_final_20250127_153334.json"
python manage.py import_articles --category-name "Endocrine & Metabolic" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Type_2_Diabetes_final_20250127_153441.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Agerelated_Macular_Degeneration_AMD_final_20250127_153422.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Amblyopia_final_20250127_153638.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Astigmatism_final_20250127_153600.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Blepharitis_final_20250127_153715.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cataracts_final_20250127_154025.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Conjunctivitis_final_20250127_153744.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Corneal_Abrasion_final_20250127_153827.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Diabetic_Retinopathy_final_20250127_154203.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Dry_Eye_Syndrome_Dry_Eye_final_20250127_154300.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Eye_Floaters_final_20250127_154108.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Glaucoma_final_20250127_154317.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hyperopia_Farsightedness_final_20250127_154328.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Keratitis_final_20250127_154542.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Keratoconus_final_20250127_154509.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Macular_Hole_final_20250127_154514.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Myopia_Nearsightedness_final_20250127_154808.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Photophobia_final_20250127_154631.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Presbyopia_final_20250127_154715.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Retinal_Detachment_final_20250127_154838.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Retinitis_Pigmentosa_final_20250127_155008.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Strabismus_final_20250127_155124.json"
python manage.py import_articles --category-name "Eye Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Uveitis_final_20250127_155149.json"
python manage.py import_articles --category-name "Genetic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cystic_Fibrosis_final_20250127_155220.json"
python manage.py import_articles --category-name "Genetic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Huntingtons_Disease_final_20250127_155215.json"
python manage.py import_articles --category-name "Genetic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sickle_Cell_Disease_final_20250127_155317.json"
python manage.py import_articles --category-name "Genetic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Marfan_Syndrome_final_20250127_162056.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Yeast_Infection_Candidiasis_final_20250127_162110.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Chickenpox_and_Shingles_VaricellaZoster_Virus_Infection_final_20250127_162016.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Clostridioides_difficile_C_diff_Infection_final_20250127_161912.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Common_Cold_final_20250127_162123.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/HIVAIDS_final_20250127_162329.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hepatitis_B_HBV_final_20250127_162300.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hepatitis_C_HCV_final_20250127_162445.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Herpes_Simplex_Virus_Infection_HSV_final_20250127_162854.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Human_Papillomavirus_HPV_Infection_final_20250127_162613.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Influenza_Flu_final_20250127_162734.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Lyme_Disease_final_20250127_162757.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Meningitis_final_20250127_162846.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Mononucleosis_Mono_final_20250127_162950.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Osteomyelitis_Bone_Infection_final_20250127_163031.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sepsis_final_20250127_163100.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Streptococcal_Pharyngitis_Strep_throat_final_20250127_163411.json"
python manage.py import_articles --category-name "Infections" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Tuberculosis_final_20250127_163407.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Chronic_Kidney_Disease_CKD_final_20250127_163353.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cirrhosis_final_20250127_163430.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hepatitis_final_20250127_163509.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/MetabolicAssociated_Steatohepatitis_final_20250127_163644.json"
python manage.py import_articles --category-name "Liver Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/MetabolicAssociated_Steatotic_Liver_Disease_final_20250127_163712.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/AttentionDeficitHyperactivity_Disorder_ADHD_final_20250127_164055.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Anxiety_Disorder_final_20250127_164148.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Aspergers_Syndrome_final_20250127_164023.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Autism_Spectrum_Disorder_final_20250127_164057.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Bipolar_Disorder_final_20250127_164159.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Depression_final_20250127_164440.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Loneliness_final_20250127_164728.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Posttraumatic_Stress_Disorder_PTSD_final_20250127_164537.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Panic_Disorder_final_20250127_164811.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Postpartum_Depression_final_20250127_164655.json"
python manage.py import_articles --category-name "Mental Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Seasonal_Affective_Disorder_final_20250127_164809.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Childhood_Obesity_final_20250127_165016.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Dyslipidemia_final_20250127_165432.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Metabolic_Syndrome_final_20250127_165148.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Obesity_final_20250127_165438.json"
python manage.py import_articles --category-name "Metabolic Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Prediabetes_final_20250127_165259.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Achilles_Tendinitis_Achilles_Tendinopathy_final_20250127_165441.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Acute_fractures_final_20250127_165451.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Ankle_Sprain_final_20250127_165625.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Anterior_Cruciate_Ligament_Tear_ACL_Tear_final_20250127_170032.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Bruises_Contusion_final_20250127_165751.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Burns_final_20250127_165917.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Bursitis_final_20250127_170128.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Frostbite_final_20250127_165930.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Medial_Epicondylitis_Golfers_Elbow_final_20250127_170026.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Growth_Plate_Fracture_final_20250127_170136.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hamstring_Injury_final_20250127_170315.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Herniated_Disc_final_20250127_170501.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Iliotibial_Band_Syndrome_final_20250127_170614.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Glenoid_Labrum_Tear_final_20250127_170501.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Little_League_Elbow_final_20250127_170656.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Little_League_Shoulder_final_20250127_170637.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Medial_Collateral_Ligament_Injury_final_20250127_171010.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Muscle_Cramp_final_20250127_170932.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/OsgoodSchlatter_Disease_final_20250127_170946.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Osteochondritis_Dissecans_final_20250127_171110.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Overtraining_Syndrome_final_20250127_171110.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Repetitive_Strain_Injury_final_20250127_171317.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Patellar_Tendinitis_final_20250127_171348.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Patellofemoral_Pain_Syndrome_PFPS_final_20250127_171548.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sacroiliac_Joint_Dysfunction_Pelvic_Pain_final_20250127_171414.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Plantar_Fasciitis_final_20250127_171502.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Rotator_Cuff_Tear_final_20250127_171746.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Scoliosis_final_20250127_171745.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Severs_Disease_Calcaneal_Apophysitis_final_20250127_171707.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Medial_Tibial_Stress_Syndrome_Shin_Splints_final_20250127_171727.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Shoulder_Dislocation_final_20250127_172045.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Spinal_Stenosis_final_20250127_172314.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Spondylolisthesis_final_20250127_172223.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sprains_and_Strains_final_20250127_172306.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Stress_Fracture_final_20250127_172217.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Lateral_Epicondylitis_Tennis_Elbow_final_20250127_172309.json"
python manage.py import_articles --category-name "Musculoskeletal" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Meniscus_Tear_final_20250127_172722.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Alzheimers_Disease_final_20250127_172730.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Carpal_Tunnel_Syndrome_final_20250127_172850.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cervical_Radiculopathy_final_20250127_172910.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cluster_Headache_final_20250127_172755.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Concussions_final_20250127_173207.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/ICU_Delirium_final_20250127_173209.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Lumbar_Radiculopathy_final_20250127_173357.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Migraine_Headache_final_20250127_173253.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Postural_Orthostatic_Tachycardia_Syndrome_POTS_final_20250127_173337.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Parkinsons_Disease_final_20250127_173558.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Peripheral_Neuropathy_final_20250127_173729.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Postherpetic_Neuralgia_Shingles_Pain_final_20250127_173721.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sciatica_final_20250127_173718.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Stroke_final_20250127_173751.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Tension_Headache_final_20250127_173857.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Trigeminal_Neuralgia_final_20250127_174037.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Vertigo_final_20250127_174432.json"
python manage.py import_articles --category-name "Neurological" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Visual_Migraine_Ocular_Migraine_final_20250127_174335.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Halitosis_Bad_Breath_final_20250127_174526.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cavities_Tooth_Decay_final_20250127_174249.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Dental_Abscess_final_20250127_174409.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Dry_Mouth_Xerostomia_final_20250127_174743.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Gingivitis_final_20250127_174814.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Mouth_Ulcers_Canker_Sores_final_20250127_174755.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Orthodontic_Relapse_final_20250127_174812.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Periodontitis_final_20250127_175025.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Dentin_Hypersensitivity_Tooth_Sensitivity_final_20250127_175028.json"
python manage.py import_articles --category-name "Oral Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Wisdom_Teeth_Impaction_final_20250127_174924.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Malaria_final_20250127_175456.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Toxoplasmosis_final_20250127_175329.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Giardiasis_final_20250127_175311.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Trichinosis_final_20250127_175403.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Lice_Infestation_Pediculosis_final_20250127_175319.json"
python manage.py import_articles --category-name "Parasitic Conditions" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Scabies_final_20250127_175746.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Endometriosis_final_20250127_180001.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Infertility_final_20250127_175841.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Menopause_Menopausal_Symptoms_final_20250127_175834.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Menstrual_Disorders_final_20250127_180441.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Polycystic_Ovary_Syndrome_PCOS_Related_Hair_Loss_final_20250127_180436.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Polycystic_Ovary_Syndrome_PCOS_final_20250127_180340.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Premenstrual_Dysphoric_Disorder_final_20250127_180237.json"
python manage.py import_articles --category-name "Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Premenstrual_Syndrome_final_20250127_180412.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Acute_Respiratory_Distress_Syndrome_ARDS_final_20250127_180732.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Asthma_final_20250127_180707.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Bronchitis_final_20250127_180808.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Chronic_Cough_final_20250127_180805.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Chronic_Obstructive_Pulmonary_Disease_COPD_final_20250127_180935.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Lung_Abscess_final_20250127_181020.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Occupational_Lung_Disease_final_20250127_181230.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Pneumoconiosis_final_20250127_181429.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Pneumonia_final_20250127_181429.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Pulmonary_Embolism_final_20250127_181341.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Pulmonary_Fibrosis_final_20250127_181517.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Pulmonary_Hypertension_final_20250127_181636.json"
python manage.py import_articles --category-name "Respiratory" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sinusitis_Sinus_Infection_final_20250127_181750.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Bacterial_Vaginosis_BV_final_20250127_182007.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Chlamydia_Infection_final_20250127_181922.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Gonorrhea_final_20250127_182132.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Syphilis_final_20250127_182020.json"
python manage.py import_articles --category-name "Sexual & Reproductive Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Trichomoniasis_final_20250127_182157.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Acne_Vulgaris_Acne_Vulgaris_final_20250127_182325.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Actinic_Keratosis_final_20250127_182404.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Albinism_final_20250127_182342.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Alopecia_Areata_final_20250127_182546.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Athletes_Foot_Tinea_Pedis_final_20250127_182514.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Boils_Furuncle_final_20250127_182639.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cellulitis_final_20250127_182659.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Contact_Dermatitis_final_20250127_182750.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Cystic_Acne_final_20250127_182947.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Eczema_Atopic_Dermatitis_final_20250127_182940.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Folliculitis_final_20250127_183018.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Alopecia_Hair_Loss_final_20250127_183027.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Urticaria_Hives_final_20250127_183211.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Hyperhidrosis_final_20250127_183417.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Tinea_Cruris_Jock_Itch_final_20250127_183340.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Keloid_final_20250127_183455.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Keratosis_Pilaris_final_20250127_183411.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Melasma_final_20250127_183535.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Postpartum_Hair_Loss_final_20250127_183539.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Psoriasis_final_20250127_183733.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Ringworm_Tinea_final_20250127_183835.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Rosacea_final_20250127_183807.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Seborrheic_Dermatitis_final_20250127_183846.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Skin_Tag_Acrochordon_final_20250127_183818.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sunburn_final_20250127_184607.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Vitiligo_final_20250127_184209.json"
python manage.py import_articles --category-name "Skin Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Wart_final_20250127_184321.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Central_Sleep_Apnea_CSA_final_20250127_184418.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Delayed_Sleep_Phase_Syndrome_final_20250127_184325.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Familial_Advanced_Sleep_Phase_Syndrome_final_20250127_184438.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Idiopathic_Hypersomnia_final_20250127_184553.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Insomnia_final_20250127_185046.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Narcolepsy_final_20250127_185332.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Night_Terrors_final_20250127_184925.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Non24Hour_SleepWake_Disorder_final_20250127_185036.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Periodic_Limb_Movement_Disorder_PLMD_final_20250127_185102.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/REM_Sleep_Behavior_Disorder_final_20250127_185227.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Restless_Legs_Syndrome_final_20250127_185443.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Shift_Work_Sleep_Disorder_final_20250127_185424.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sleep_Apnea_final_20250127_185457.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sleep_Bruxism_Teeth_Grinding_final_20250127_185507.json"
python manage.py import_articles --category-name "Sleep Disorders" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Sleepwalking_final_20250127_185638.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Interstitial_Cystitis_final_20250127_185851.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Urinary_Tract_Infection_UTI_final_20250127_185852.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Nephrolithiasis_Kidney_Stones_final_20250127_190054.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Urinary_Incontinence_final_20250127_185950.json"
python manage.py import_articles --category-name "Urinary Health" --json-path "/home/vrothenberg_salk_edu/wagtail/data/final_json/Prostatitis_final_20250127_190048.json"
