# Generated by Django 5.1.4 on 2024-12-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeBaseIndexPage',
            new_name='IndexPage',
        ),
    ]
