# Generated by Django 5.1.4 on 2024-12-13 01:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_rename_knowledgebaseindexpage_indexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='body',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='alternative_therapies',
            field=wagtail.fields.RichTextField(blank=True, help_text='Complementary treatments.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='causes',
            field=wagtail.fields.RichTextField(blank=True, help_text='Underlying mechanisms or causes.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='complications',
            field=wagtail.fields.RichTextField(blank=True, help_text='Potential health challenges.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='diagnosis',
            field=wagtail.fields.RichTextField(blank=True, help_text='The diagnostic process.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='faqs',
            field=wagtail.fields.RichTextField(blank=True, help_text='Frequently asked questions.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='home_care',
            field=wagtail.fields.RichTextField(blank=True, help_text='Self-management and lifestyle tips.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='key_facts',
            field=wagtail.fields.RichTextField(blank=True, help_text='Notable statistics or key data.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='living_with',
            field=wagtail.fields.RichTextField(blank=True, help_text='Guidance for long-term management.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='overview',
            field=wagtail.fields.RichTextField(blank=True, help_text='A high-level introduction to the topic.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='prevention',
            field=wagtail.fields.RichTextField(blank=True, help_text='Practical advice for risk reduction.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='references',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sources and citations.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='risk_factors',
            field=wagtail.fields.RichTextField(blank=True, help_text='Factors that increase susceptibility.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='specialists',
            field=wagtail.fields.RichTextField(blank=True, help_text='Healthcare providers for diagnosis and treatment.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='symptoms',
            field=wagtail.fields.RichTextField(blank=True, help_text='Common signs and symptoms.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='treatment',
            field=wagtail.fields.RichTextField(blank=True, help_text='Medical and therapeutic interventions.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='types',
            field=wagtail.fields.RichTextField(blank=True, help_text='Classifications or subtypes.'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='A brief introduction to the article.'),
        ),
    ]
