# Generated by Django 5.1.4 on 2024-12-13 18:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_remove_articlepage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='alternative_therapies',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='causes',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='complications',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='home_care',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='key_facts',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='living_with',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='prevention',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='references',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='risk_factors',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='specialists',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='types',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='_search_description',
            field=models.CharField(blank=True, db_column='search_description', help_text='A brief description for search results.', max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short introduction to the article.'),
        ),
    ]
