# Generated by Django 5.1.4 on 2024-12-16 18:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_remove_articlepage_alternative_therapies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='_search_description',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category this article belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledgebase.categorypage'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('key_facts', 6), ('faqs', 7), ('references', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading Text', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('level', 1)]], {}), 3: ('knowledgebase.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Fact'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Key Facts'}), 6: ('wagtail.blocks.StructBlock', [[('content', 5)]], {}), 7: ('knowledgebase.blocks.FAQListBlock', (), {}), 8: ('knowledgebase.blocks.ReferenceListBlock', (), {})}, verbose_name='Article Content'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro',
            field=models.TextField(blank=True, help_text='A short introductory description or subtitle.'),
        ),
    ]
