# Generated by Django 5.1.4 on 2024-12-16 23:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0007_alter_articlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('rich_text', 3), ('bullet_points', 4), ('key_facts', 7), ('faqs', 8), ('references', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading Text', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('level', 1)]], {}), 3: ('knowledgebase.blocks.RichTextBlock', (), {}), 4: ('knowledgebase.blocks.BulletPointBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Fact'}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Key Facts'}), 7: ('wagtail.blocks.StructBlock', [[('content', 6)]], {}), 8: ('knowledgebase.blocks.FAQListBlock', (), {}), 9: ('knowledgebase.blocks.ReferenceListBlock', (), {})}, verbose_name='Article Content'),
        ),
    ]
