# Generated by Django 5.1.4 on 2025-01-16 20:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0008_alter_articlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('markdown', 3), ('rich_text', 4), ('bullet_points', 5), ('key_facts', 8), ('faqs', 9), ('references', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading Text', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('level', 1)]], {}), 3: ('knowledgebase.blocks.MarkdownBlock', (), {}), 4: ('knowledgebase.blocks.RichTextBlock', (), {}), 5: ('knowledgebase.blocks.BulletPointBlock', (), {}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Fact'}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Key Facts'}), 8: ('wagtail.blocks.StructBlock', [[('content', 7)]], {}), 9: ('knowledgebase.blocks.FAQListBlock', (), {}), 10: ('knowledgebase.blocks.ReferenceListBlock', (), {})}, verbose_name='Article Content'),
        ),
    ]
