# Generated by Django 5.1.4 on 2025-01-22 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0009_alter_articlepage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='review_date',
            field=models.DateTimeField(blank=True, help_text='Date the article was last reviewed. Defaults to the last published date.', null=True, verbose_name='Review Date'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Reviewed'),
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('credentials', models.CharField(blank=True, max_length=255, verbose_name='Credentials')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Reviewer',
                'verbose_name_plural': 'Reviewers',
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledgebase.reviewer', verbose_name='Reviewer'),
        ),
    ]
